# Generated by Django 2.1.3 on 2019-05-01 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='valuationMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
                ('annualRevenue', models.FloatField()),
                ('yoyGrowth', models.DecimalField(decimal_places=3, max_digits=5)),
                ('capitalSeeking', models.IntegerField()),
                ('monthlyBurn', models.IntegerField()),
                ('investmentPeriod', models.IntegerField()),
                ('industryMultiplier', models.IntegerField(choices=[(1, 5), (2, 10), (3, 15), (4, 20), (5, 25)])),
                ('outstandingShares', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
