# Generated by Django 2.1.3 on 2019-05-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_valuationmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationmetrics',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
