# Generated by Django 2.1.3 on 2019-05-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_valuationmetrics_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuationmetrics',
            name='annualRevenue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='valuationmetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
