# Generated by Django 2.1.3 on 2019-05-02 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20190502_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuationmetrics',
            name='id',
        ),
        migrations.AlterField(
            model_name='valuationmetrics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
