# Generated by Django 2.1.3 on 2019-05-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_auto_20190502_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuationmetrics',
            name='industryVertical',
            field=models.CharField(default='software', max_length=150),
        ),
    ]
